project:
  type: website
  output-dir: docs

website:
  title: "Vidigi - Auto Documentation"
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - section: "Modules"
        contents:
          - 01_animation_facade_animate_activity_log_.qmd
          - 02_event_log_.qmd
          - 03_layout_configuration_event_position_df_.qmd
          - 04_simpy_resource_enhancement_customresource_store_populate_store_.qmd
          - 05_snapshot_preparation_reshape_for_animations_generate_animation_df_.qmd
          - 06_animation_generation_generate_animation_.qmd

format:
  html:
    theme: cosmo
    toc: true
